NUMPY
======

--------------------

## numpy의 특징

* Numerical Python의 약자
* 고성능 과학 계산용 페키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅 가능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하고 빠르고 편리
* 데이터 과학 도구에 대한 갱태계의 핵심을 이루고 있음

In [10]:
import numpy as np
print(np.__version__)

In [13]:

a1 = np.array([1, 2, 3, 4 ,5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[2], a1[3], a1[4])
a1[0] = 4
a1[1] = 5
a1[2] = 6
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 6 4 5]


> 1차원 배열을 만들었습니다.

In [6]:
a2 = np.array([ [1,2,3], [4,5,6], [7,8,9]])
print(a2)
print(a2.shape)
print(a2[0,0], a2[1,1], a2[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


> 2차원 배열을 만들었습니다.

In [8]:
a3 = np.array([ [ [1,2,3], [4,5,6], [7,8,9] ],
                   [ [1,2,3], [4,5,6], [7,8,9] ],
                   [ [1,2,3], [4,5,6], [7,8,9] ] ])
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


> 3차원 배열을 만들었습니다.

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])